<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create user
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">UserName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userName", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserlastname" class="col-sm-2 control-label">UserLastName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userLastName", "size" => 30, "class" => "form-control", "id" => "fieldUserlastname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserfirstname" class="col-sm-2 control-label">UserFirstName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userFirstName", "size" => 30, "class" => "form-control", "id" => "fieldUserfirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsermiddlename" class="col-sm-2 control-label">UserMiddleName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userMiddleName", "size" => 30, "class" => "form-control", "id" => "fieldUsermiddlename"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserpassword" class="col-sm-2 control-label">UserPassword</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["userPassword", [], "class" => "form-control", "id" => "fieldUserpassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserlastlogin" class="col-sm-2 control-label">UserLastLogin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userLastLogin", "size" => 30, "class" => "form-control", "id" => "fieldUserlastlogin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserinvalidloginattempt" class="col-sm-2 control-label">UserInvalidLoginAttempt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userInvalidLoginAttempt", "type" => "number", "class" => "form-control", "id" => "fieldUserinvalidloginattempt"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserlastpasswordchange" class="col-sm-2 control-label">UserLastPasswordChange</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userLastPasswordChange", "size" => 30, "class" => "form-control", "id" => "fieldUserlastpasswordchange"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUseremail" class="col-sm-2 control-label">UserEmail</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userEmail", "size" => 30, "class" => "form-control", "id" => "fieldUseremail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserteam" class="col-sm-2 control-label">UserTeam</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userTeam", "size" => 30, "class" => "form-control", "id" => "fieldUserteam"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatestatus" class="col-sm-2 control-label">CreateStatus</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["createStatus", [], "class" => "form-control", "id" => "fieldCreatestatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedby" class="col-sm-2 control-label">CreatedBy</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["createdBy", "size" => 30, "class" => "form-control", "id" => "fieldCreatedby"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
