<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>UserID</th>
            <th>UserName</th>
            <th>UserLastName</th>
            <th>UserFirstName</th>
            <th>UserMiddleName</th>
            <th>UserPassword</th>
            <th>UserLastLogin</th>
            <th>UserInvalidLoginAttempt</th>
            <th>UserLastPasswordChange</th>
            <th>UserEmail</th>
            <th>UserTeam</th>
            <th>CreateStatus</th>
            <th>CreatedBy</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->userID ?></td>
            <td><?php echo $user->userName ?></td>
            <td><?php echo $user->userLastName ?></td>
            <td><?php echo $user->userFirstName ?></td>
            <td><?php echo $user->userMiddleName ?></td>
            <td><?php echo $user->userPassword ?></td>
            <td><?php echo $user->userLastLogin ?></td>
            <td><?php echo $user->userInvalidLoginAttempt ?></td>
            <td><?php echo $user->userLastPasswordChange ?></td>
            <td><?php echo $user->userEmail ?></td>
            <td><?php echo $user->userTeam ?></td>
            <td><?php echo $user->createStatus ?></td>
            <td><?php echo $user->createdBy ?></td>

                <td><?php echo $this->tag->linkTo(["user/edit/" . $user->userID, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->userID, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
